
services:
  reber:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: db
    image: postgres:16.1
    environment:
      POSTGRES_DB: reber
      POSTGRES_USER: reber
      POSTGRES_PASSWORD: reber
    volumes:
      - ./data:/data
